apiVersion: apps/v1
kind: Deployment
metadata:
  name:  netflix-app
  #namespace: nginx-argocd
spec:
  selector:
    matchLabels:
      app:  netflix-app
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app:  netflix-app
    spec:
      containers:
      - name:  netflix-app
        image: sanjeev0181/netflix
        ports:
        - containerPort: 80
